# Generated by Django 2.2.10 on 2021-08-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='description',
            new_name='quiz_specification',
        ),
    ]
